/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


#pragma mark - NativeTunerTunerResult

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeTunerTunerResult {
  P0 hasPitch{};
  P1 frequency{};
  P2 midiNote{};
  P3 cents{};
  P4 amplitude;
  bool operator==(const NativeTunerTunerResult &other) const {
    return hasPitch == other.hasPitch && frequency == other.frequency && midiNote == other.midiNote && cents == other.cents && amplitude == other.amplitude;
  }
};

template <typename T>
struct NativeTunerTunerResultBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.hasPitch)>(rt, value.getProperty(rt, "hasPitch"), jsInvoker),
      bridging::fromJs<decltype(types.frequency)>(rt, value.getProperty(rt, "frequency"), jsInvoker),
      bridging::fromJs<decltype(types.midiNote)>(rt, value.getProperty(rt, "midiNote"), jsInvoker),
      bridging::fromJs<decltype(types.cents)>(rt, value.getProperty(rt, "cents"), jsInvoker),
      bridging::fromJs<decltype(types.amplitude)>(rt, value.getProperty(rt, "amplitude"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static bool hasPitchToJs(jsi::Runtime &rt, decltype(types.hasPitch) value) {
    return bridging::toJs(rt, value);
  }
  static double frequencyToJs(jsi::Runtime &rt, decltype(types.frequency) value) {
    return bridging::toJs(rt, value);
  }
  static double midiNoteToJs(jsi::Runtime &rt, decltype(types.midiNote) value) {
    return bridging::toJs(rt, value);
  }
  static double centsToJs(jsi::Runtime &rt, decltype(types.cents) value) {
    return bridging::toJs(rt, value);
  }
  static double amplitudeToJs(jsi::Runtime &rt, decltype(types.amplitude) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "hasPitch", bridging::toJs(rt, value.hasPitch, jsInvoker));
    result.setProperty(rt, "frequency", bridging::toJs(rt, value.frequency, jsInvoker));
    result.setProperty(rt, "midiNote", bridging::toJs(rt, value.midiNote, jsInvoker));
    result.setProperty(rt, "cents", bridging::toJs(rt, value.cents, jsInvoker));
    result.setProperty(rt, "amplitude", bridging::toJs(rt, value.amplitude, jsInvoker));
    return result;
  }
};


template <typename T>
class JSI_EXPORT NativeTunerCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "NativeTuner";

protected:
  NativeTunerCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeTunerCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["processFrame"] = MethodMetadata {.argCount = 1, .invoker = __processFrame};
    methodMap_["getLatestResult"] = MethodMetadata {.argCount = 0, .invoker = __getLatestResult};
  }
  
private:
  static jsi::Value __processFrame(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::processFrame) == 2,
      "Expected processFrame(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::processFrame,  static_cast<NativeTunerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asObject(rt).asArray(rt));return jsi::Value::undefined();
  }

  static jsi::Value __getLatestResult(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getLatestResult) == 1,
      "Expected getLatestResult(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Object>(rt, &T::getLatestResult,  static_cast<NativeTunerCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }
};

} // namespace facebook::react
