package com.mytuner.specs;

import androidx.annotation.NonNull;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.WritableMap;

// This class is expected to be generated by React Native Codegen.
// After running codegen, ensure that NativeTunerSpec is in this package
// and that the method signatures match.
public class NativeTunerModule extends NativeTunerSpec {
  static {
    System.loadLibrary("tuner");
  }

  private final long nativeHandle;

  public NativeTunerModule(ReactApplicationContext reactContext) {
    super(reactContext);
    nativeHandle = initNative(44100);
  }

  @NonNull
  @Override
  public String getName() {
    return "TunerEngine";
  }

  @Override
  public void processFrame(@NonNull ReadableArray buffer) {
    int size = buffer.size();
    float[] frame = new float[size];
    for (int i = 0; i < size; i++) {
      frame[i] = (float) buffer.getDouble(i);
    }
    processFrameNative(nativeHandle, frame);
  }

  @NonNull
  @Override
  public WritableMap getLatestResult() {
    return getLatestResultNative(nativeHandle);
  }

  @Override
  public void invalidate() {
    super.invalidate();
    destroyNative(nativeHandle);
  }

  // JNI bridge
  private static native long initNative(int sampleRate);
  private static native void processFrameNative(long handle, float[] frame);
  private static native WritableMap getLatestResultNative(long handle);
  private static native void destroyNative(long handle);
}

